alter table public.purchase_payments
  add column if not exists payment_number bigint generated by default as identity;

update public.purchase_payments
set payment_number = nextval(pg_get_serial_sequence('public.purchase_payments', 'payment_number'))
where payment_number is null;

alter table public.purchase_payments
  alter column payment_number set not null;

alter table public.purchase_payments
  alter column payment_number set generated always;

create index if not exists purchase_payments_payment_number_idx
  on public.purchase_payments(payment_number);

create unique index if not exists purchase_payments_payment_number_key
  on public.purchase_payments(payment_number);
