create table if not exists public.staff_members (
  id uuid primary key default gen_random_uuid(),
  employee_number bigint generated by default as identity unique,
  profile_id uuid unique references public.profiles(id) on delete set null,
  full_name text not null check (length(btrim(full_name)) > 0),
  phone text,
  secondary_phone text,
  job_title text not null check (length(btrim(job_title)) > 0),
  department text not null check (department in ('service', 'cashier', 'kitchen', 'management', 'cleaning', 'barista', 'shisha', 'other')),
  employment_type text not null default 'full_time' check (employment_type in ('full_time', 'part_time', 'temporary')),
  shift_type text not null default 'fixed' check (shift_type in ('morning', 'evening', 'night', 'rotating', 'fixed')),
  hire_date date,
  birth_date date,
  salary numeric(12,0) check (salary is null or salary >= 0),
  address text,
  emergency_contact_name text,
  emergency_contact_phone text,
  notes text,
  status text not null default 'active' check (status in ('active', 'on_leave', 'inactive', 'terminated')),
  has_system_access boolean not null default false,
  created_by uuid references public.profiles(id),
  updated_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists staff_members_status_idx on public.staff_members(status);
create index if not exists staff_members_department_idx on public.staff_members(department);
create index if not exists staff_members_profile_id_idx on public.staff_members(profile_id);

drop trigger if exists set_staff_members_updated_at on public.staff_members;
create trigger set_staff_members_updated_at before update on public.staff_members
  for each row execute function public.set_updated_at();

insert into public.staff_members (profile_id, full_name, job_title, department, status, has_system_access)
select
  p.id,
  p.full_name,
  case p.role
    when 'captain' then '?????'
    when 'cashier' then '?????'
    when 'kitchen' then '???'
    when 'admin' then '???? ??????'
    else '????'
  end,
  case p.role
    when 'captain' then 'service'
    when 'cashier' then 'cashier'
    when 'kitchen' then 'kitchen'
    when 'admin' then 'management'
    else 'other'
  end,
  'active',
  true
from public.profiles p
on conflict (profile_id) do nothing;

alter table public.staff_members enable row level security;

drop policy if exists "staff admin read" on public.staff_members;
create policy "staff admin read" on public.staff_members
  for select to authenticated
  using (public.current_user_role() = 'admin');

drop policy if exists "staff own read" on public.staff_members;
create policy "staff own read" on public.staff_members
  for select to authenticated
  using (profile_id = auth.uid());

drop policy if exists "staff admin insert" on public.staff_members;
create policy "staff admin insert" on public.staff_members
  for insert to authenticated
  with check (public.current_user_role() = 'admin');

drop policy if exists "staff admin update" on public.staff_members;
create policy "staff admin update" on public.staff_members
  for update to authenticated
  using (public.current_user_role() = 'admin')
  with check (public.current_user_role() = 'admin');

create or replace function public.is_valid_staff_department(value text)
returns boolean
language sql
immutable
as $$ select value in ('service', 'cashier', 'kitchen', 'management', 'cleaning', 'barista', 'shisha', 'other') $$;

create or replace function public.is_valid_employment_type(value text)
returns boolean
language sql
immutable
as $$ select value in ('full_time', 'part_time', 'temporary') $$;

create or replace function public.is_valid_shift_type(value text)
returns boolean
language sql
immutable
as $$ select value in ('morning', 'evening', 'night', 'rotating', 'fixed') $$;

create or replace function public.is_valid_staff_status(value text)
returns boolean
language sql
immutable
as $$ select value in ('active', 'on_leave', 'inactive', 'terminated') $$;

create or replace function public.assert_active_admin()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  admin_profile public.profiles%rowtype;
begin
  select * into admin_profile from public.profiles where id = auth.uid();

  if not found or admin_profile.role <> 'admin' or admin_profile.status <> 'active' then
    raise exception 'Only active admin users can manage staff';
  end if;
end;
$$;

create or replace function public.create_staff_member(
  p_full_name text,
  p_phone text default null,
  p_secondary_phone text default null,
  p_job_title text default null,
  p_department text default 'other',
  p_employment_type text default 'full_time',
  p_shift_type text default 'fixed',
  p_hire_date date default null,
  p_birth_date date default null,
  p_salary numeric default null,
  p_address text default null,
  p_emergency_contact_name text default null,
  p_emergency_contact_phone text default null,
  p_notes text default null
)
returns public.staff_members
language plpgsql
security definer
set search_path = public
as $$
declare
  created_staff public.staff_members%rowtype;
begin
  perform public.assert_active_admin();

  if nullif(btrim(p_full_name), '') is null or length(btrim(p_full_name)) < 2 then
    raise exception 'Staff full name is required';
  end if;

  if nullif(btrim(coalesce(p_job_title, '')), '') is null then
    raise exception 'Job title is required';
  end if;

  if not public.is_valid_staff_department(p_department) then raise exception 'Invalid staff department'; end if;
  if not public.is_valid_employment_type(p_employment_type) then raise exception 'Invalid employment type'; end if;
  if not public.is_valid_shift_type(p_shift_type) then raise exception 'Invalid shift type'; end if;
  if p_salary is not null and p_salary < 0 then raise exception 'Salary must be positive'; end if;
  if p_birth_date is not null and p_birth_date > current_date then raise exception 'Birth date cannot be in the future'; end if;

  insert into public.staff_members (
    full_name, phone, secondary_phone, job_title, department, employment_type, shift_type,
    hire_date, birth_date, salary, address, emergency_contact_name, emergency_contact_phone,
    notes, has_system_access, created_by, updated_by
  ) values (
    btrim(p_full_name), nullif(btrim(coalesce(p_phone, '')), ''), nullif(btrim(coalesce(p_secondary_phone, '')), ''),
    btrim(p_job_title), p_department, p_employment_type, p_shift_type,
    p_hire_date, p_birth_date, p_salary, nullif(btrim(coalesce(p_address, '')), ''),
    nullif(btrim(coalesce(p_emergency_contact_name, '')), ''), nullif(btrim(coalesce(p_emergency_contact_phone, '')), ''),
    nullif(btrim(coalesce(p_notes, '')), ''), false, auth.uid(), auth.uid()
  ) returning * into created_staff;

  perform public.write_audit_log('create_staff_member', 'staff_members', created_staff.id, null, to_jsonb(created_staff));
  return created_staff;
end;
$$;

create or replace function public.update_staff_member(
  p_staff_id uuid,
  p_full_name text,
  p_phone text default null,
  p_secondary_phone text default null,
  p_job_title text default null,
  p_department text default 'other',
  p_employment_type text default 'full_time',
  p_shift_type text default 'fixed',
  p_hire_date date default null,
  p_birth_date date default null,
  p_salary numeric default null,
  p_address text default null,
  p_emergency_contact_name text default null,
  p_emergency_contact_phone text default null,
  p_notes text default null
)
returns public.staff_members
language plpgsql
security definer
set search_path = public
as $$
declare
  old_staff public.staff_members%rowtype;
  updated_staff public.staff_members%rowtype;
begin
  perform public.assert_active_admin();

  select * into old_staff from public.staff_members where id = p_staff_id for update;
  if not found then raise exception 'Staff member not found'; end if;
  if nullif(btrim(p_full_name), '') is null or length(btrim(p_full_name)) < 2 then raise exception 'Staff full name is required'; end if;
  if nullif(btrim(coalesce(p_job_title, '')), '') is null then raise exception 'Job title is required'; end if;
  if not public.is_valid_staff_department(p_department) then raise exception 'Invalid staff department'; end if;
  if not public.is_valid_employment_type(p_employment_type) then raise exception 'Invalid employment type'; end if;
  if not public.is_valid_shift_type(p_shift_type) then raise exception 'Invalid shift type'; end if;
  if p_salary is not null and p_salary < 0 then raise exception 'Salary must be positive'; end if;
  if p_birth_date is not null and p_birth_date > current_date then raise exception 'Birth date cannot be in the future'; end if;

  update public.staff_members
  set full_name = btrim(p_full_name),
      phone = nullif(btrim(coalesce(p_phone, '')), ''),
      secondary_phone = nullif(btrim(coalesce(p_secondary_phone, '')), ''),
      job_title = btrim(p_job_title),
      department = p_department,
      employment_type = p_employment_type,
      shift_type = p_shift_type,
      hire_date = p_hire_date,
      birth_date = p_birth_date,
      salary = p_salary,
      address = nullif(btrim(coalesce(p_address, '')), ''),
      emergency_contact_name = nullif(btrim(coalesce(p_emergency_contact_name, '')), ''),
      emergency_contact_phone = nullif(btrim(coalesce(p_emergency_contact_phone, '')), ''),
      notes = nullif(btrim(coalesce(p_notes, '')), ''),
      updated_by = auth.uid()
  where id = p_staff_id
  returning * into updated_staff;

  perform public.write_audit_log('update_staff_member', 'staff_members', p_staff_id, to_jsonb(old_staff), to_jsonb(updated_staff));
  return updated_staff;
end;
$$;

create or replace function public.update_staff_status(p_staff_id uuid, p_status text)
returns public.staff_members
language plpgsql
security definer
set search_path = public
as $$
declare
  old_staff public.staff_members%rowtype;
  updated_staff public.staff_members%rowtype;
begin
  perform public.assert_active_admin();
  if not public.is_valid_staff_status(p_status) then raise exception 'Invalid staff status'; end if;

  select * into old_staff from public.staff_members where id = p_staff_id for update;
  if not found then raise exception 'Staff member not found'; end if;

  update public.staff_members
  set status = p_status,
      updated_by = auth.uid()
  where id = p_staff_id
  returning * into updated_staff;

  if updated_staff.profile_id is not null then
    update public.profiles
    set status = case when p_status in ('active', 'on_leave') then 'active' else 'inactive' end
    where id = updated_staff.profile_id;
  end if;

  perform public.write_audit_log('update_staff_status', 'staff_members', p_staff_id, to_jsonb(old_staff), to_jsonb(updated_staff));
  return updated_staff;
end;
$$;

create or replace function public.update_staff_system_access(p_staff_id uuid, p_is_active boolean)
returns public.staff_members
language plpgsql
security definer
set search_path = public
as $$
declare
  old_staff public.staff_members%rowtype;
  updated_staff public.staff_members%rowtype;
begin
  perform public.assert_active_admin();
  select * into old_staff from public.staff_members where id = p_staff_id for update;
  if not found or old_staff.profile_id is null then raise exception 'Staff profile is not linked'; end if;
  if old_staff.status = 'terminated' and p_is_active then raise exception 'Terminated staff cannot be reactivated for system access'; end if;

  update public.profiles
  set status = case when p_is_active then 'active' else 'inactive' end
  where id = old_staff.profile_id;

  update public.staff_members
  set has_system_access = p_is_active,
      updated_by = auth.uid()
  where id = p_staff_id
  returning * into updated_staff;

  perform public.write_audit_log('update_staff_system_access', 'staff_members', p_staff_id, to_jsonb(old_staff), to_jsonb(updated_staff));
  return updated_staff;
end;
$$;
